name: gen_keycodes
description: Generates keycode source files from various resources.

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  args: null
  http: null
  path: null
  platform: null

# PUBSPEC CHECKSUM: 0000
