include: ../analysis_options.yaml

linter:
  rules:
    avoid_catches_without_on_clauses: true
    avoid_print: false # TODO enable
    public_member_api_docs: false # TODO enable
    unawaited_futures: true
