name: sample_catalog
description: A collection of Flutter sample apps
dependencies:
  flutter:
    sdk: flutter
  image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
