name: flutter_tools
description: Tools for building Flutter applications
homepage: https://flutter.dev
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  archive: 2.0.11
  args: 1.5.2
  dwds: 2.0.1
  completion: 0.2.2
  coverage: 0.13.9
  crypto: 2.1.3
  file: 5.1.0
  flutter_template_images: 1.0.0
  http: 0.12.0+4
  intl: 0.16.1
  json_rpc_2: 2.1.0
  meta: 1.1.8
  multicast_dns: 0.2.2
  mustache_template: 1.0.0+1
  package_config: 1.9.1
  platform: 2.2.1
  process: 3.0.12
  quiver: 2.0.5
  stack_trace: 1.9.3
  stream_channel: 2.0.0
  usage: 3.4.1
  webdriver: 2.1.2
  web_socket_channel: 1.1.0
  webkit_inspection_protocol: 0.5.0+1
  xml: 3.5.0
  yaml: 2.2.0
  native_stack_traces: 0.2.2
  build_daemon: 2.1.3
  flutter_goldens_client:
    path: ../flutter_goldens_client

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so when upgrading
  # this, make sure the tests are still running correctly.
  test_api: 0.2.15
  test_core: 0.3.3

  vm_service: 4.0.0

dev_dependencies:
  collection: 1.14.11
  mockito: 4.1.1
  file_testing: 2.1.0
  test: 1.14.2
  pubspec_parse: 0.1.5

  checked_yaml: 1.0.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  json_annotation: 3.0.1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  multi_server_socket: 1.0.2 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  node_preamble: 1.4.8 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"

dependency_overrides:
  dwds:
    git:
      url: https://github.com/dart-lang/webdev
      path: dwds


dartdoc:
  # Exclude this package from the hosted API docs.
  nodoc: true

# PUBSPEC CHECKSUM: 8b7f
