name: flutter_tools
description: Tools for building Flutter applications
homepage: https://flutter.dev
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  archive: 2.0.10
  args: 1.5.2
  dwds:
  completion: 0.2.1+1
  coverage:
  crypto: 2.0.6
  file: 5.0.8+1
  http: 0.12.0+2
  intl: 0.15.8
  json_rpc_2: 2.1.0
  linter: 0.1.93
  meta: 1.1.7
  multicast_dns: 0.1.1
  mustache: 1.1.1
  package_config: 1.0.5
  platform: 2.2.0
  plugin: 0.2.0+3
  process: 3.0.9
  quiver: 2.0.3
  stack_trace: 1.9.3
  stream_channel: 2.0.0
  usage: 3.4.1
  vm_service_client: 0.2.6+2
  web_socket_channel: 1.0.14
  webkit_inspection_protocol: ^0.4.0
  xml: 3.5.0
  webdev: any
  yaml: 2.1.16
  flutter_goldens_client:
    path: ../flutter_goldens_client
  protobuf: 0.13.15

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so when upgrading
  # this, make sure the tests are still running correctly.
  test_api: 0.2.5
  test_core: 0.2.5

  # Code generation dependencies
  build_runner_core:
  dart_style: 1.2.9
  code_builder: 3.2.0
  build:
  build_modules:
  build_daemon:
  build_web_compilers:

dev_dependencies:
  collection: 1.14.11
  mockito: 4.1.0
  file_testing: 2.1.0
  test:
  build_runner:
  build_vm_compilers:
  build_test:

dartdoc:
  # Exclude this package from the hosted API docs.
  nodoc: true

# PUBSPEC CHECKSUM: f131
