name: external_ui
description: A test of Flutter integrating external UIs.

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_build:
    sdk: flutter
  inject:
    git:
      url: https://github.com/jonahwilliams/inject.dart
      path: package/inject

dev_dependencies:
  build_runner: 1.2.1
  inject_generator:
    git:
      url: https://github.com/jonahwilliams/inject.dart
      path: package/inject_generator

flutter:
  uses-material-design: true

# PUBSPEC CHECKSUM: 28dd
