# Describes the targets run in continuous integration environment.
#
# Flutter infra uses this file to generate a checklist of tasks to be performed
# for every commit.
#
# More information at:
#  * https://github.com/flutter/cocoon/blob/main/CI_YAML.md
enabled_branches:
  - master
  - flutter-\d+\.\d+-candidate\.\d+

platform_properties:
  staging_build_linux:
    properties:
      dependencies: >-
        [
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Ubuntu
      cores: "8"
      device_type: none
      ignore_flakiness: "true"
  linux:
    properties:
      dependencies: >-
        [
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Ubuntu
      cores: "8"
      device_type: none
  linux_build_test:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "open_jdk", "version": "version:11"},
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Ubuntu
      cores: "8"
      device_type: none
  linux_android:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "open_jdk", "version": "version:11"},
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Linux
      device_type: "msm8952"

  linux_pixel_7pro:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "open_jdk", "version": "version:11"},
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Linux
      device_type: "Pixel 7 Pro"

  linux_samsung_a02:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "open_jdk", "version": "version:11"},
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Linux
      device_type: "SM-A025V"

  mac:
    properties:
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:2022_to_2023"}
        ]
      os: Mac-12
      device_type: none
      $flutter/osx_sdk : >-
        {
          "sdk_version": "14e300c"
        }
  mac_arm64:
    properties:
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:2022_to_2023"}
        ]
      os: Mac-12
      device_type: none
      cpu: arm64
      $flutter/osx_sdk : >-
        {
          "sdk_version": "14e300c"
        }
  mac_benchmark:
    properties:
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:2022_to_2023"}
        ]
      device_type: none
      mac_model: "Macmini8,1"
      os: Mac-12
      tags: >
        ["devicelab", "hostonly", "mac"]
      $flutter/osx_sdk : >-
        {
          "sdk_version": "14e300c"
        }
  mac_x64:
    properties:
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:2022_to_2023"}
        ]
      os: Mac-12
      device_type: none
      cpu: x86
      $flutter/osx_sdk : >-
        {
          "sdk_version": "14e300c"
        }
  mac_build_test:
    properties:
      dependencies: >-
        [
          {"dependency": "gems", "version": "v3.3.14"},
          {"dependency": "apple_signing", "version": "version:2022_to_2023"}
        ]
      os: Mac-12
      device_type: none
      cpu: x86
      $flutter/osx_sdk : >-
        {
          "sdk_version": "14e300c"
        }
  mac_android:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "open_jdk", "version": "version:11"}
        ]
      os: Mac-12
      cpu: x86
      device_type: "msm8952"
  mac_arm64_android:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "open_jdk", "version": "version:11"}
        ]
      os: Mac-12
      cpu: arm64
      device_type: "msm8952"
  mac_ios:
    properties:
      dependencies: >-
        [
          {"dependency": "gems", "version": "v3.3.14"},
          {"dependency": "apple_signing", "version": "version:2022_to_2023"}
        ]
      os: Mac-12
      cpu: x86
      device_os: iOS-16
      $flutter/osx_sdk : >-
        {
          "sdk_version": "14e300c"
        }
  mac_arm64_ios:
    properties:
      dependencies: >-
        [
          {"dependency": "gems", "version": "v3.3.14"},
          {"dependency": "apple_signing", "version": "none"}
        ]
      os: Mac-12
      cpu: arm64
      device_os: iOS-16
      $flutter/osx_sdk : >-
        {
          "sdk_version": "14e300c"
        }
  windows:
    properties:
      dependencies: >-
        [
          {"dependency": "certs", "version": "version:9563bb"}
        ]
      os: Windows-10
      device_type: none
  windows_arm64:
    properties:
      dependencies: >-
        [
          {"dependency": "certs", "version": "version:9563bb"}
        ]
      os: Windows
      cpu: arm64
  windows_android:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "certs", "version": "version:9563bb"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "open_jdk", "version": "version:11"}
        ]
      os: Windows-10
      device_type: "msm8952"

targets:
  - name: Linux web_tests_0
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "goldctl", "version": "git_revision:f808dcff91b221ae313e540c09d79696cd08b8de"}
        ]
      shard: web_tests
      subshard: "0"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
      # Retry for flakes caused by https://github.com/flutter/flutter/issues/132654
      presubmit_max_attempts: "1"
    runIf:
      - dev/**
      - packages/**
      - bin/**
      - .ci.yaml

  - name: Linux web_tests_1
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "goldctl", "version": "git_revision:f808dcff91b221ae313e540c09d79696cd08b8de"}
        ]
      shard: web_tests
      subshard: "1"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
      # Retry for flakes caused by https://github.com/flutter/flutter/issues/132654
      presubmit_max_attempts: "1"
    runIf:
      - dev/**
      - packages/**
      - bin/**
      - .ci.yaml

  - name: Linux web_tests_2
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "goldctl", "version": "git_revision:f808dcff91b221ae313e540c09d79696cd08b8de"}
        ]
      shard: web_tests
      subshard: "2"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
      # Retry for flakes caused by https://github.com/flutter/flutter/issues/132654
      presubmit_max_attempts: "1"
    runIf:
      - dev/**
      - packages/**
      - bin/**
      - .ci.yaml

  - name: Linux web_tests_3
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "goldctl", "version": "git_revision:f808dcff91b221ae313e540c09d79696cd08b8de"}
        ]
      shard: web_tests
      subshard: "3"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
      # Retry for flakes caused by https://github.com/flutter/flutter/issues/132654
      presubmit_max_attempts: "1"
    runIf:
      - dev/**
      - packages/**
      - bin/**
      - .ci.yaml

  - name: Linux web_tests_4
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "goldctl", "version": "git_revision:f808dcff91b221ae313e540c09d79696cd08b8de"}
        ]
      shard: web_tests
      subshard: "4"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
      # Retry for flakes caused by https://github.com/flutter/flutter/issues/132654
      presubmit_max_attempts: "1"
    runIf:
      - dev/**
      - packages/**
      - bin/**
      - .ci.yaml

  - name: Linux web_tests_5
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "goldctl", "version": "git_revision:f808dcff91b221ae313e540c09d79696cd08b8de"}
        ]
      shard: web_tests
      subshard: "5"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
      # Retry for flakes caused by https://github.com/flutter/flutter/issues/132654
      presubmit_max_attempts: "1"
    runIf:
      - dev/**
      - packages/**
      - bin/**
      - .ci.yaml

  - name: Linux web_tests_6
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "goldctl", "version": "git_revision:f808dcff91b221ae313e540c09d79696cd08b8de"}
        ]
      shard: web_tests
      subshard: "6"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
      # Retry for flakes caused by https://github.com/flutter/flutter/issues/132654
      presubmit_max_attempts: "1"
    runIf:
      - dev/**
      - packages/**
      - bin/**
      - .ci.yaml

  - name: Linux web_tests_7_last
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "goldctl", "version": "git_revision:f808dcff91b221ae313e540c09d79696cd08b8de"}
        ]
      shard: web_tests
      subshard: "7_last"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
      # Retry for flakes caused by https://github.com/flutter/flutter/issues/132654
      presubmit_max_attempts: "1"
    runIf:
      - dev/**
      - packages/**
      - bin/**
      - .ci.yaml

  - name: Linux web_canvaskit_tests_0
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "goldctl", "version": "git_revision:f808dcff91b221ae313e540c09d79696cd08b8de"}
        ]
      shard: web_canvaskit_tests
      subshard: "0"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
      # Retry for flakes caused by https://github.com/flutter/flutter/issues/132654
      presubmit_max_attempts: "1"
    runIf:
      - dev/**
      - packages/**
      - bin/**
      - .ci.yaml

  - name: Linux web_canvaskit_tests_1
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "goldctl", "version": "git_revision:f808dcff91b221ae313e540c09d79696cd08b8de"}
        ]
      shard: web_canvaskit_tests
      subshard: "1"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
      # Retry for flakes caused by https://github.com/flutter/flutter/issues/132654
      presubmit_max_attempts: "1"
    runIf:
      - dev/**
      - packages/**
      - bin/**
      - .ci.yaml

  - name: Linux web_canvaskit_tests_2
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "goldctl", "version": "git_revision:f808dcff91b221ae313e540c09d79696cd08b8de"}
        ]
      shard: web_canvaskit_tests
      subshard: "2"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
      # Retry for flakes caused by https://github.com/flutter/flutter/issues/132654
      presubmit_max_attempts: "1"
    runIf:
      - dev/**
      - packages/**
      - bin/**
      - .ci.yaml

  - name: Linux web_canvaskit_tests_3
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "goldctl", "version": "git_revision:f808dcff91b221ae313e540c09d79696cd08b8de"}
        ]
      shard: web_canvaskit_tests
      subshard: "3"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
      # Retry for flakes caused by https://github.com/flutter/flutter/issues/132654
      presubmit_max_attempts: "1"
    runIf:
      - dev/**
      - packages/**
      - bin/**
      - .ci.yaml

  - name: Linux web_canvaskit_tests_4
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "goldctl", "version": "git_revision:f808dcff91b221ae313e540c09d79696cd08b8de"}
        ]
      shard: web_canvaskit_tests
      subshard: "4"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
      # Retry for flakes caused by https://github.com/flutter/flutter/issues/132654
      presubmit_max_attempts: "1"
    runIf:
      - dev/**
      - packages/**
      - bin/**
      - .ci.yaml

  - name: Linux web_canvaskit_tests_5
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "goldctl", "version": "git_revision:f808dcff91b221ae313e540c09d79696cd08b8de"}
        ]
      shard: web_canvaskit_tests
      subshard: "5"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
      # Retry for flakes caused by https://github.com/flutter/flutter/issues/132654
      presubmit_max_attempts: "1"
    runIf:
      - dev/**
      - packages/**
      - bin/**
      - .ci.yaml

  - name: Linux web_canvaskit_tests_6
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "goldctl", "version": "git_revision:f808dcff91b221ae313e540c09d79696cd08b8de"}
        ]
      shard: web_canvaskit_tests
      subshard: "6"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
      # Retry for flakes caused by https://github.com/flutter/flutter/issues/132654
      presubmit_max_attempts: "1"
    runIf:
      - dev/**
      - packages/**
      - bin/**
      - .ci.yaml

  - name: Linux web_canvaskit_tests_7_last
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:117.0"},
          {"dependency": "goldctl", "version": "git_revision:f808dcff91b221ae313e540c09d79696cd08b8de"}
        ]
      shard: web_canvaskit_tests
      subshard: "7_last"
      tags: >
        ["framework", "hostonly", "shard", "linux"]
      # Retry for flakes caused by https://github.com/flutter/flutter/issues/132654
      presubmit_max_attempts: "1"
    runIf:
      - dev/**
      - packages/**
      - bin/**
      - .ci.yaml