# Describes the targets run in continuous integration environment.
#
# Flutter infra uses this file to generate a checklist of tasks to be performed
# for every commit.
#
# More information at:
#  * https://github.com/flutter/cocoon/blob/main/CI_YAML.md
enabled_branches:
  - master
  - flutter-\d+\.\d+-candidate\.\d+

platform_properties:
  staging_build_linux:
    properties:
      dependencies: >-
        [
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Ubuntu
      cores: "8"
      device_type: none
      ignore_flakiness: "true"
  linux:
    properties:
      dependencies: >-
        [
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Ubuntu
      cores: "8"
      device_type: none
  linux_build_test:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "open_jdk", "version": "version:11"},
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Ubuntu
      cores: "8"
      device_type: none
  linux_android:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "open_jdk", "version": "version:11"},
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Linux
      device_type: "msm8952"

  linux_pixel_7pro:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "open_jdk", "version": "version:11"},
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Linux
      device_type: "Pixel 7 Pro"

  linux_samsung_a02:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "open_jdk", "version": "version:11"},
          {"dependency": "curl", "version": "version:7.64.0"}
        ]
      os: Linux
      device_type: "SM-A025V"

  mac:
    properties:
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:2022_to_2023"}
        ]
      os: Mac-12
      device_type: none
      $flutter/osx_sdk : >-
        {
          "sdk_version": "14e300c"
        }
  mac_arm64:
    properties:
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:2022_to_2023"}
        ]
      os: Mac-12
      device_type: none
      cpu: arm64
      $flutter/osx_sdk : >-
        {
          "sdk_version": "14e300c"
        }
  mac_benchmark:
    properties:
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:2022_to_2023"}
        ]
      device_type: none
      mac_model: "Macmini8,1"
      os: Mac-12
      tags: >
        ["devicelab", "hostonly", "mac"]
      $flutter/osx_sdk : >-
        {
          "sdk_version": "14e300c"
        }
  mac_x64:
    properties:
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:2022_to_2023"}
        ]
      os: Mac-12
      device_type: none
      cpu: x86
      $flutter/osx_sdk : >-
        {
          "sdk_version": "14e300c"
        }
  mac_build_test:
    properties:
      dependencies: >-
        [
          {"dependency": "ruby", "version": "ruby_3.1-pod_1.13"},
          {"dependency": "apple_signing", "version": "version:2022_to_2023"}
        ]
      os: Mac-13
      device_type: none
      cpu: x86
      $flutter/osx_sdk : >-
        {
          "sdk_version": "14e300c"
        }
  mac_android:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "chrome_and_driver", "version": "version:119.0.6045.9"},
          {"dependency": "open_jdk", "version": "version:11"}
        ]
      os: Mac-12
      cpu: x86
      device_type: "msm8952"
  mac_arm64_android:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "open_jdk", "version": "version:11"}
        ]
      os: Mac-12
      cpu: arm64
      device_type: "msm8952"
  mac_ios:
    properties:
      dependencies: >-
        [
          {"dependency": "ruby", "version": "ruby_3.1-pod_1.13"},
          {"dependency": "apple_signing", "version": "version:2022_to_2023"}
        ]
      os: Mac-12
      cpu: x86
      device_os: iOS-16
      $flutter/osx_sdk : >-
        {
          "sdk_version": "14e300c"
        }
  mac_arm64_ios:
    properties:
      dependencies: >-
        [
          {"dependency": "ruby", "version": "ruby_3.1-pod_1.13"},
          {"dependency": "apple_signing", "version": "none"}
        ]
      os: Mac-12
      cpu: arm64
      device_os: iOS-16
      $flutter/osx_sdk : >-
        {
          "sdk_version": "14e300c"
        }
  windows:
    properties:
      dependencies: >-
        [
          {"dependency": "certs", "version": "version:9563bb"}
        ]
      os: Windows-10
      device_type: none
  windows_arm64:
    properties:
      # The arch can be removed after https://github.com/flutter/flutter/issues/135722.
      arch: arm
      dependencies: >-
        [
          {"dependency": "certs", "version": "version:9563bb"}
        ]
      os: Windows
      cpu: arm64
  windows_android:
    properties:
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:33v6"},
          {"dependency": "certs", "version": "version:9563bb"},
          {"dependency": "chrome_and_driver", "version": "version:119.0.6045.9"},
          {"dependency": "open_jdk", "version": "version:11"}
        ]
      os: Windows-10
      device_type: "msm8952"

targets:
  - name: Mac_build_test flutter_gallery__transition_perf_e2e_ios
    recipe: devicelab/devicelab_drone_build_test
    timeout: 60
    properties:
      tags: >
        ["devicelab", "ios", "mac"]
      task_name: flutter_gallery__transition_perf_e2e_ios
      drone_dimensions: >
        ["device_os=iOS-16","os=Mac-13", "cpu=x86"]
