# CIRRUS CONFIGURATION FILE

env:
  # We change Flutter's directory to include a space in its name (see
  # $CIRRUS_WORKING_DIR) so that we constantly test path names with
  # spaces in them. The FLUTTER_SDK_PATH_WITH_SPACE variable must
  # therefore have a space in it.
  FLUTTER_SDK_PATH_WITH_SPACE: "flutter sdk"
  GCLOUD_SERVICE_ACCOUNT_KEY: ENCRYPTED[f12abe60f5045d619ef4c79b83dd1e0722a0b0b13dbea95fbe334e2db7fffbcd841a5a92da8824848b539a19afe0c9fb]
  BOT: "true"

clean_commit_message_script:
  # Unsetting CIRRUS_CHANGE_MESSAGE and CIRRUS_COMMIT_MESSAGE as they
  # might include non-ASCII characters which makes Gradle crash.
  # See: https://github.com/flutter/flutter/issues/24935
  # TODO(amirha): remove once we've migrated to newer Gradle
  - echo "$CIRRUS_CHANGE_MESSAGE" > /tmp/cirrus_change_message.txt
  - echo "$CIRRUS_COMMIT_MESSAGE" > /tmp/cirrus_commit_message.txt
  - export CIRRUS_CHANGE_MESSAGE=""
  - export CIRRUS_COMMIT_MESSAGE=""

# LINUX SHARDS
task:
  container:
    image: gcr.io/flutter-cirrus/build-flutter-image:latest
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_PR == ''
  env:
    CIRRUS_WORKING_DIR: "/tmp/$FLUTTER_SDK_PATH_WITH_SPACE"
    PATH: "$CIRRUS_WORKING_DIR/bin:$CIRRUS_WORKING_DIR/bin/cache/dart-sdk/bin:$PATH"
    ANDROID_SDK_ROOT: "/opt/android_sdk"
  pub_cache:
    folder: $HOME/.pub-cache
    fingerprint_script: echo $OS; grep -r --include=pubspec.yaml 'PUBSPEC CHECKSUM' "$CIRRUS_WORKING_DIR"
  flutter_pkg_cache:
    folder: bin/cache/pkg
    fingerprint_script: echo $OS; cat bin/internal/*.version
  artifacts_cache:
    folder: bin/cache/artifacts
    fingerprint_script: echo $OS; cat bin/internal/*.version
  setup_script:
    - date
    - git clean -xffd
    - git fetch origin
    - git fetch origin master # To set FETCH_HEAD, so that "git merge-base" works.
    - flutter config --no-analytics
    - flutter doctor -v
    - flutter update-packages
    - ./dev/bots/accept_android_sdk_licenses.sh
    - date
  on_failure:
    failure_script:
      - date
      - which flutter
  matrix:
    - name: analyze-linux # linux-only
      script:
        - dart --enable-asserts ./dev/bots/analyze.dart

    - name: framework_tests_widgets-linux
      container:
        cpu: 4
        memory: 12G
      env:
        SHARD: framework_tests
        SUBSHARD: widgets
        GOLDCTL: "$CIRRUS_WORKING_DIR/depot_tools/goldctl"
        GOLD_SERVICE_ACCOUNT: ENCRYPTED[3afeea5ac7201151c3d0dc9648862f0462b5e4f55dc600ca8b692319622f7c3eda3d577b1b16cc2ef0311b7314c1c095]
      script:
        - ./dev/bots/download_goldctl.sh
        - dart --enable-asserts ./dev/bots/test.dart

    - name: framework_tests_libraries-linux
      container:
        cpu: 4
        memory: 12G
      env:
        SHARD: framework_tests
        SUBSHARD: libraries
        GOLDCTL: "$CIRRUS_WORKING_DIR/depot_tools/goldctl"
        GOLD_SERVICE_ACCOUNT: ENCRYPTED[3afeea5ac7201151c3d0dc9648862f0462b5e4f55dc600ca8b692319622f7c3eda3d577b1b16cc2ef0311b7314c1c095]
      script:
        - ./dev/bots/download_goldctl.sh
        - dart --enable-asserts ./dev/bots/test.dart

    - name: framework_tests_misc-linux
      container:
        cpu: 4
        memory: 12G
      env:
        SHARD: framework_tests
        SUBSHARD: misc
      script:
        - dart --enable-asserts ./dev/bots/test.dart

    - name: tool_tests_general-linux
      container:
        cpu: 4
        memory: 12G
      env:
        SHARD: tool_tests
        SUBSHARD: general
      script:
        - dart --enable-asserts ./dev/bots/test.dart

    - name: tool_tests_commands-linux
      container:
        cpu: 4
        memory: 12G
      env:
        SHARD: tool_tests
        SUBSHARD: commands
      script:
        - dart --enable-asserts ./dev/bots/test.dart

    - name: tool_tests_integration-linux
      container:
        cpu: 4
        memory: 12G
      env:
        SHARD: tool_tests
        SUBSHARD: integration
      script:
        - dart --enable-asserts ./dev/bots/test.dart

    - name: tool_coverage-linux # linux-only
      skip: "!changesInclude('packages/flutter_tools/**/*.dart') && $CIRRUS_BRANCH != 'master'"
      container:
        cpu: 8
        memory: 24G
      env:
        CODECOV_TOKEN: ENCRYPTED[7c76a7f8c9264f3b7f3fd63fcf186f93c62c4dfe43ec288861c2f506d456681032b89efe7b7a139c82156350ca2c752c]
        SHARD: tool_coverage
      script:
        - dart --enable-asserts ./dev/bots/test.dart
        - bash <(curl -s https://codecov.io/bash) -c -f packages/flutter_tools/coverage/lcov.info -F flutter_tool

    # TODO(jonahwilliams): re-enabled once we've determined causes for flakiness
    # - name: web_tests-linux
    #   container:
    #     cpu: 4
    #     memory: 12G
    #   env:
    #     SHARD: web_tests
    #   script:
    #     - dart --enable-asserts ./dev/bots/test.dart

    - name: build_tests-linux
      env:
        SHARD: build_tests
      script:
        - dart --enable-asserts ./dev/bots/test.dart

    - name: integration_tests_gradle1-linux
      container:
        cpu: 4
        memory: 12G
      env:
        SHARD: integration_tests
        SUBSHARD: gradle1
      script:
        - dart --enable-asserts ./dev/bots/test.dart

    - name: integration_tests_gradle2-linux
      container:
        cpu: 4
        memory: 12G
      env:
        SHARD: integration_tests
        SUBSHARD: gradle2
      script:
        - dart --enable-asserts ./dev/bots/test.dart

    - name: integration_tests_misc-linux
      container:
        cpu: 4
        memory: 12G
      env:
        SHARD: integration_tests
        SUBSHARD: misc
      script:
        - dart --enable-asserts ./dev/bots/test.dart

    # TODO(ianh): add_to_app-linux

    - name: docs-linux # linux-only
      env:
        # For uploading master docs to Firebase master branch staging site
        FIREBASE_MASTER_TOKEN: ENCRYPTED[eb768d18798fdc5abfe09b224e1724c4d82831d715ccf90df2c79d618c317216cbd99493278361f6fe7948b409b603f0]
        # For uploading beta docs to Firebase public live site
        FIREBASE_PUBLIC_TOKEN: ENCRYPTED[37e8b82f167864cae9a3f4d2cf3f37dea331d9375c295327c45de524f6c588fa6f6d63e5784f10f6d43ce29689f36c92]
      script:
        - ./dev/bots/docs.sh

    - name: customer_testing-linux
      script:
        - rm -rf bin/cache/pkg/tests
        - git clone https://github.com/flutter/tests.git bin/cache/pkg/tests
        - dart --enable-asserts dev/customer_testing/run_tests.dart --skip-on-fetch-failure --skip-template bin/cache/pkg/tests/registry/*.test

    - name: release_smoke_tests-linux # linux-only
      env:
        CLOUDSDK_CORE_DISABLE_PROMPTS: 1
        GCLOUD_FIREBASE_TESTLAB_KEY: ENCRYPTED[1c140257edc48f5578fa5a0e5038b84c8e53270c405efa5a8e35ea303a4e0d135853989f448f72136206de854d17fbec]
      script:
        - ./dev/bots/firebase_testlab.sh

    - name: deploy_gallery-linux # linux- and macos- only
      depends_on:
        - analyze-linux
        - framework_tests_widgets-linux
        - framework_tests_libraries-linux
        - framework_tests_misc-linux
        - tool_tests_general-linux
        - tool_tests_commands-linux
        - tool_tests_integration-linux
        - build_tests-linux
        - integration_tests_gradle1-linux
        - integration_tests_gradle2-linux
        - integration_tests_misc-linux
        - release_smoke_tests-linux
      env:
        GOOGLE_DEVELOPER_SERVICE_ACCOUNT_ACTOR_FASTLANE: ENCRYPTED[d9ac1462c3c556fc2f8165c9d5566a16497d8ebc38a50357f7f3abf136b7f83e1d1d76dde36fee356cb0f9ebf7a89346]
        ANDROID_GALLERY_UPLOAD_KEY: ENCRYPTED[0f2aca35f05b26add5d9edea2a7449341269a2b7e22d5c667f876996e2e8bc44ff1369431ebf73b7c5581fd95d0e5902]
      script:
        - ./dev/bots/deploy_gallery.sh

# WINDOWS SHARDS
task:
  windows_container:
    image: cirrusci/android-sdk:28-windowsservercore-2019
    os_version: 2019
    cpu: 4
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_PR == ''
  env:
    CIRRUS_WORKING_DIR: "C:\\Windows\\Temp\\$FLUTTER_SDK_PATH_WITH_SPACE"
    PATH: "$CIRRUS_WORKING_DIR/bin;$CIRRUS_WORKING_DIR/bin/cache/dart-sdk/bin;$PATH"
  pub_cache:
    folder: $APPDATA\Pub\Cache
    fingerprint_script:
      - ps:  $Env:OS; Get-ChildItem -Path "$Env:CIRRUS_WORKING_DIR" pubspec.yaml -Recurse | Select-String -Pattern "PUBSPEC CHECKSUM" -SimpleMatch
  flutter_pkg_cache:
    folder: bin\cache\pkg
    fingerprint_script: echo %OS% & type bin\internal\*.version
  artifacts_cache:
    folder: bin\cache\artifacts
    fingerprint_script: echo %OS% & type bin\internal\*.version
  setup_script:
    - git clean -xffd
    - git fetch origin
    - git fetch origin master # To set FETCH_HEAD, so that "git merge-base" works.
    - flutter config --no-analytics
    - flutter doctor -v
    - flutter update-packages
    - git fetch origin master
  matrix:
    - name: framework_tests_widgets-windows
      env:
        SHARD: framework_tests
        SUBSHARD: widgets
        GOLDCTL: "C:\\Windows\\Temp\\depot_tools\\goldctl.exe"
        GOLD_SERVICE_ACCOUNT: ENCRYPTED[3afeea5ac7201151c3d0dc9648862f0462b5e4f55dc600ca8b692319622f7c3eda3d577b1b16cc2ef0311b7314c1c095]
      script:
        - powershell dev\bots\download_goldctl.ps1
        - dart --enable-asserts dev\bots\test.dart

    - name: framework_tests_libraries-windows
      env:
        SHARD: framework_tests
        SUBSHARD: libraries
        GOLDCTL: "C:\\Windows\\Temp\\depot_tools\\goldctl.exe"
        GOLD_SERVICE_ACCOUNT: ENCRYPTED[3afeea5ac7201151c3d0dc9648862f0462b5e4f55dc600ca8b692319622f7c3eda3d577b1b16cc2ef0311b7314c1c095]
      script:
        - powershell dev\bots\download_goldctl.ps1
        - dart --enable-asserts dev\bots\test.dart

    - name: framework_tests_misc-windows
      env:
        SHARD: framework_tests
        SUBSHARD: misc
      script:
        - dart --enable-asserts dev\bots\test.dart

    - name: tool_tests_general-windows
      env:
        SHARD: tool_tests
        SUBSHARD: general
      script:
        - dart --enable-asserts ./dev/bots/test.dart

    - name: tool_tests_commands-windows
      env:
        SHARD: tool_tests
        SUBSHARD: commands
      script:
        - dart --enable-asserts ./dev/bots/test.dart

    - name: tool_tests_integration-windows
      env:
        SHARD: tool_tests
        SUBSHARD: integration
      script:
        - dart --enable-asserts ./dev/bots/test.dart

    # TODO(jonahwilliams): web_tests-windows

    - name: build_tests-windows
      env:
        SHARD: build_tests
      container:
        cpu: 4
        memory: 12G
      script:
        - dart --enable-asserts dev\bots\test.dart

    # TODO(ianh): integration_tests_gradle1-windows requires https://github.com/flutter/flutter/issues/36311

    # TODO(ianh): integration_tests_gradle2-windows requires https://github.com/flutter/flutter/issues/36311

    - name: integration_tests_misc-windows
      container:
        cpu: 4
        memory: 12G
      env:
        SHARD: integration_tests
        SUBSHARD: misc
      script:
        - dart --enable-asserts dev\bots\test.dart

    # TODO(ianh): add_to_app-windows

    - name: customer_testing-windows
      script:
        - CMD /S /C "IF EXIST "bin\cache\pkg\tests\" RMDIR /S /Q bin\cache\pkg\tests"
        - git clone https://github.com/flutter/tests.git bin\cache\pkg\tests
        - dart --enable-asserts dev\customer_testing\run_tests.dart --skip-on-fetch-failure --skip-template bin/cache/pkg/tests/registry/*.test
    - name: integration_tests_gradle1-windows
      env:
        SHARD: integration_tests
        SUBSHARD: gradle1
      test_script:
        - dart --enable-asserts dev\bots\test.dart
      container:
        cpu: 4
        memory: 12G
    - name: integration_tests_gradle2-windows
      env:
        SHARD: integration_tests
        SUBSHARD: gradle2
      test_script:
        - dart --enable-asserts dev\bots\test.dart
      container:
        cpu: 4
        memory: 12G

# MACOS SHARDS
task:
  osx_instance:
    image: mojave-xcode-10.2-flutter # see https://cirrus-ci.org/guide/macOS/ for list of images (we should update regularly)
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' # even for PRs, because otherwise you only get one VM at a time
  env:
    CIRRUS_WORKING_DIR: "/tmp/$FLUTTER_SDK_PATH_WITH_SPACE"
    FLUTTER_FRAMEWORK_DIR: "$CIRRUS_WORKING_DIR/bin/cache/artifacts/engine/ios/"
    PATH: "$CIRRUS_WORKING_DIR/bin:$CIRRUS_WORKING_DIR/bin/cache/dart-sdk/bin:$PATH"
    COCOAPODS_DISABLE_STATS: true
  pub_cache:
    folder: $HOME/.pub-cache
    fingerprint_script: echo $OS; grep -r --include=pubspec.yaml 'PUBSPEC CHECKSUM' "$CIRRUS_WORKING_DIR"
  flutter_pkg_cache:
    folder: bin/cache/pkg
    fingerprint_script: echo $OS; cat bin/internal/*.version
  artifacts_cache:
    folder: bin/cache/artifacts
    fingerprint_script: echo $OS; cat bin/internal/*.version
  setup_script:
    - date
    - which flutter
    - sudo gem install cocoapods
    - git clean -xffd
    - git fetch origin
    - git fetch origin master # To set FETCH_HEAD, so that "git merge-base" works.
    - flutter config --no-analytics
    - flutter doctor -v
    - flutter update-packages
    - date
    - which flutter
  on_failure:
    failure_script:
      - date
      - which flutter
  matrix:
    - name: framework_tests_widgets-macos
      env:
        SHARD: framework_tests
        SUBSHARD: widgets
        GOLDCTL: "$CIRRUS_WORKING_DIR/depot_tools/goldctl"
        GOLD_SERVICE_ACCOUNT: ENCRYPTED[3afeea5ac7201151c3d0dc9648862f0462b5e4f55dc600ca8b692319622f7c3eda3d577b1b16cc2ef0311b7314c1c095]
      script:
        - ulimit -S -n 2048 # https://github.com/flutter/flutter/issues/2976
        - ./dev/bots/download_goldctl.sh
        - dart --enable-asserts dev/bots/test.dart

    - name: framework_tests_libraries-macos
      env:
        SHARD: framework_tests
        SUBSHARD: libraries
        GOLDCTL: "$CIRRUS_WORKING_DIR/depot_tools/goldctl"
        GOLD_SERVICE_ACCOUNT: ENCRYPTED[3afeea5ac7201151c3d0dc9648862f0462b5e4f55dc600ca8b692319622f7c3eda3d577b1b16cc2ef0311b7314c1c095]
      script:
        - ulimit -S -n 2048 # https://github.com/flutter/flutter/issues/2976
        - ./dev/bots/download_goldctl.sh
        - dart --enable-asserts dev/bots/test.dart

    - name: framework_tests_misc-macos
      env:
        SHARD: framework_tests
        SUBSHARD: misc
      script:
        - ulimit -S -n 2048 # https://github.com/flutter/flutter/issues/2976
        - dart --enable-asserts dev/bots/test.dart

    - name: tool_tests_general-macos
      env:
        SHARD: tool_tests
        SUBSHARD: general
      script:
        - ulimit -S -n 2048 # https://github.com/flutter/flutter/issues/2976
        - dart --enable-asserts ./dev/bots/test.dart

    - name: tool_tests_commands-macos
      env:
        SHARD: tool_tests
        SUBSHARD: commands
      script:
        - ulimit -S -n 2048 # https://github.com/flutter/flutter/issues/2976
        - dart --enable-asserts ./dev/bots/test.dart

    - name: tool_tests_integration-macos
      env:
        SHARD: tool_tests
        SUBSHARD: integration
      script:
        - ulimit -S -n 2048 # https://github.com/flutter/flutter/issues/2976
        - dart --enable-asserts ./dev/bots/test.dart

    # TODO(jonahwilliams): web_tests-macos

    - name: build_tests-macos
      env:
        SHARD: build_tests
      script:
        - ulimit -S -n 2048 # https://github.com/flutter/flutter/issues/2976
        - dart --enable-asserts dev/bots/test.dart

    - name: integration_tests_gradle1-macos
      env:
        SHARD: integration_tests
        SUBSHARD: gradle1
      script:
        - ulimit -S -n 2048 # https://github.com/flutter/flutter/issues/2976
        - dart --enable-asserts ./dev/bots/test.dart

    - name: integration_tests_gradle2-macos
      env:
        SHARD: integration_tests
        SUBSHARD: gradle2
      script:
        - ulimit -S -n 2048 # https://github.com/flutter/flutter/issues/2976
        - dart --enable-asserts ./dev/bots/test.dart

    - name: integration_tests_misc-macos
      env:
        SHARD: integration_tests
        SUBSHARD: misc
      script:
        - ulimit -S -n 2048 # https://github.com/flutter/flutter/issues/2976
        - dart --enable-asserts ./dev/bots/test.dart

    - name: add_to_app-macos
      env:
        SHARD: add_to_app_tests
      script:
        - ulimit -S -n 2048 # https://github.com/flutter/flutter/issues/2976
        - dart --enable-asserts dev/bots/test.dart

    - name: customer_testing-macos
      script:
        - ulimit -S -n 2048 # https://github.com/flutter/flutter/issues/2976
        - rm -rf bin/cache/pkg/tests
        - git clone https://github.com/flutter/tests.git bin/cache/pkg/tests
        - dart --enable-asserts dev/customer_testing/run_tests.dart --skip-on-fetch-failure --skip-template bin/cache/pkg/tests/registry/*.test

    - name: deploy_gallery-macos # linux- and macos- only
      depends_on:
        - analyze-linux
        - framework_tests_widgets-macos
        - framework_tests_libraries-macos
        - framework_tests_misc-macos
        - tool_tests_general-macos
        - tool_tests_commands-macos
        - tool_tests_integration-macos
        - build_tests-macos
        - integration_tests_gradle1-macos
        - integration_tests_gradle2-macos
        - integration_tests_misc-macos
      env:
        # Apple Fastlane password.
        FASTLANE_PASSWORD: ENCRYPTED[4b1f0b8d52874e9de965acd46c79743f3b81f3a513614179b9be7cf53dc8258753e257bdadb11a298ee455259df21865]
        # Private repo for publishing certificates.
        PUBLISHING_MATCH_CERTIFICATE_REPO: ENCRYPTED[3c0e78877d933fc80107aa6f3790fd1cf927250b852d6cb53202be696b4903ed8ca839b809626aaf18050bf7e436fab7]
        PUBLISHING_MATCH_REPO_TOKEN: ENCRYPTED[3d1230b744c6ed6c788a91bec741b769401dbcd426b18f9af8080bfeefdfc21913ca4047980c5b5b7ce823f12e7b6b19]
        # Apple Certificates Match Passphrase
        MATCH_PASSWORD: ENCRYPTED[db07f252234397090e3ec59152d9ec1831f5ecd0ef97d247b1dca757bbb9ef9b7c832a39bce2caf1949ccdf097e59a73]
      script:
        - ulimit -S -n 2048 # https://github.com/flutter/flutter/issues/2976
        - ./dev/bots/deploy_gallery.sh

docker_builder:
  # Only build a new docker image when we tag a release (for dev, beta, or release.)
  only_if: $CIRRUS_TAG != ''
  env:
    GCLOUD_CREDENTIALS: ENCRYPTED[f7c098d4dd7f5ee1bfee0bb7e944cce72efbe10e97ad6440ae72de4de6a1c24d23f421a2619c668e94377fb64b0bb3e6]
  depends_on:
    - docs-linux
    - analyze-linux
    - framework_tests_widgets-linux
    - framework_tests_libraries-linux
    - framework_tests_misc-linux
    - tool_tests_general-linux
    - tool_tests_commands-linux
    - tool_tests_integration-linux
    - build_tests-linux
    - integration_tests_gradle1-linux
    - integration_tests_gradle2-linux
    - integration_tests_misc-linux
    - release_smoke_tests-linux
  script:
    - "$CIRRUS_WORKING_DIR/dev/ci/docker_linux/docker_build.sh"
    - "$CIRRUS_WORKING_DIR/dev/ci/docker_linux/docker_login.sh"
    - "$CIRRUS_WORKING_DIR/dev/ci/docker_linux/docker_push.sh"

restore_commit_message_script:
  - export CIRRUS_CHANGE_MESSAGE=`cat /tmp/cirrus_change_message.txt`
  - export CIRRUS_COMMIT_MESSAGE=`cat /tmp/cirrus_commit_message.txt`
