task:
  container:
    image: gcr.io/flutter-cirrus/build-flutter-image:latest
  use_compute_credits: true
  env:
    CIRRUS_WORKING_DIR: "/tmp/flutter sdk"
    PATH: "$CIRRUS_WORKING_DIR/bin:$CIRRUS_WORKING_DIR/bin/cache/dart-sdk/bin:$PATH"
    ANDROID_SDK_ROOT: "/opt/android_sdk"
  git_fetch_script:
    - git clean -xfd
    - git fetch origin
    - git fetch origin master
  setup_script: ./dev/bots/cirrus_setup.sh
  matrix:
    - name: tool_tests_general-linux
      env:
        SHARD: tool_tests
        SUBSHARD: general
      test_script:
        - dart --enable-asserts ./dev/bots/test.dart
      container:
        cpu: 4
        memory: 12G
