sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6 # sky_shell binary depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
before_script:
  - ./travis/setup.sh
script:
  - ./travis/test.sh
cache:
  directories:
    - $HOME/.pub-cache
