name: flutter_web_plugins
description: Library to register Flutter Web plugins
author: Flutter Authors <flutter-dev@googlegroups.com>
homepage: http://flutter.dev

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"
