name: image_loading
description: Integration testing library for Android semantics

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: 1.6.0

  mockito:

flutter:
  uses-material-design: true

# PUBSPEC CHECKSUM: c371
