name: customer_testing
description: Tool to run the tests listed in the flutter/tests repository.

environment:
  sdk: any

dependencies:
  args: null
  path: null
  glob: null
  meta: null

# PUBSPEC CHECKSUM: 0000
