# Temporary work-around for breaking changes to `directives_ordering`

include: ../analysis_options.yaml

linter:
  rules:
    # Disable temporarily to unblock an SDK roll (https://github.com/flutter/flutter/issues/84577)
    directives_ordering: false
