name: fake
description: A fake pubpsec.yaml to trick the analyzer into thinking this is a package, reading analysis_options.yaml, and skipping this directory.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
