name: asset_transformation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  capitalizer_transformer:
    path: ./capitalizer_transformer

flutter:
  uses-material-design: true
  assets:
    - path: assets/test_asset.txt
      transformers:
        - package: capitalizer_transformer
