# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  flutter:
    import: "package:build_modules/builders.dart"
    builder_factories:
      - metaModuleBuilderFactoryForPlatform('flutter')
      - metaModuleCleanBuilderFactoryForPlatform('flutter')
      - moduleBuilderFactoryForPlatform('flutter')
    applies_builders: ["build_modules|module_cleanup"]
    is_optional: True
    auto_apply: none
    required_inputs: [".dart", ".module.library"]
  kernel:
    import: "package:flutter_build/flutter_build.dart"
    builder_factories:
      - "flutterKernelBuilder"
    build_extensions:
      ".dart":
        - ".app.dill"
        - ".packages"
    auto_apply: root_package
    build_to: cache
    defaults:
      generate_for:
        include:
          - lib/**
