name: gradle_deprecated_settings
description: Integration test for the current settings.gradle.

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: 0.5.8+2

flutter:
  uses-material-design: true

# PUBSPEC CHECKSUM: 0e1d
