builders:
  dartdevc:
    import: "package:build_modules/builders.dart"
    builder_factories:
      - metaModuleBuilderFactoryForPlatform('flutter_dartdevc')
      - metaModuleCleanBuilderFactoryForPlatform('flutter_dartdevc')
      - moduleBuilderFactoryForPlatform('flutter_dartdevc')
      - unlinkedSummaryBuilderForPlatform('flutter_dartdevc')
      - linkedSummaryBuilderForPlatform('flutter_dartdevc')
    build_extensions:
      $lib$:
        - .flutter_dartdevc.meta_module.raw
        - .flutter_dartdevc.meta_module.clean
      .dart:
        - .flutter_dartdevc.module
        - .flutter_dartdevc.linked.sum
        - .flutter_dartdevc.unlinked.sum
    is_optional: True
    auto_apply: none
    required_inputs: [".dart", ".module.library"]
    applies_builders: ["build_modules|module_cleanup"]
  ddc:
    import: "package:_builders/builders.dart"
    builder_factories:
      - devCompilerBuilder
    build_extensions:
      .dart:
        - .ddc.js.errors
        - .ddc.js
        - .ddc.js.map
    is_optional: True
    auto_apply: all_packages
    required_inputs:
      - .dart
      - .flutter_dartdevc.module
    applies_builders: ["_builders|dartdevc"]
  entrypoint:
    import: "package:_builders/builders.dart"
    builder_factories:
      - webEntrypointBuilder
    build_extensions:
      .dart:
        - .dart.bootstrap.js
        - .dart.js
        - .dart.js.map
        - .dart.js.tar.gz
    required_inputs:
      - .dart
      - .ddc.js
      - .flutter_dartdevc.module
    build_to: cache
    auto_apply: root_package
    applies_builders:
      - _builders|ddc
    defaults:
      generate_for:
        include:
          - web/**
          - test/**_test.dart
          - example/**
          - benchmark/**
        exclude:
          - test/**.node_test.dart
          - test/**.vm_test.dart
