name: _builders

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  build: 1.1.1
  build_modules: 
  build_web_compilers: