name: _builders

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  build: any
  build_modules: any
  build_web_compilers: any

dependency_overrides:
  build:
    path: /Users/jonahwilliams/Documents/build/build/
  build_modules:
    path: /Users/jonahwilliams/Documents/build/build_modules/
  build_web_compilers:
    path: /Users/jonahwilliams/Documents/build/build_web_compilers/