name: flutter_view
description: A new flutter project.

dependencies:
  flutter:
    sdk: flutter

  async: 2.0.6 # TRANSITIVE DEPENDENCY
  charcode: 1.1.1 # TRANSITIVE DEPENDENCY
  collection: 1.14.6 # TRANSITIVE DEPENDENCY
  http: 0.11.3+16 # TRANSITIVE DEPENDENCY
  http_parser: 3.1.1 # TRANSITIVE DEPENDENCY
  meta: 1.1.2 # TRANSITIVE DEPENDENCY
  path: 1.5.1 # TRANSITIVE DEPENDENCY
  source_span: 1.4.0 # TRANSITIVE DEPENDENCY
  string_scanner: 1.0.2 # TRANSITIVE DEPENDENCY
  typed_data: 1.1.5 # TRANSITIVE DEPENDENCY
  vector_math: 2.0.5 # TRANSITIVE DEPENDENCY

flutter:
  uses-material-design: true
  assets:
    - assets/flutter-mark-square-64.png
