include: ../../analysis_options.yaml

linter:
  rules:
    use_super_parameters: false # TODO(goderbauer): enable when super params are a little more established, https://github.com/flutter/flutter/issues/101068
