name: flutter_devicelab
author: Flutter Authors <flutter-dev@googlegroups.com>
description: Flutter continuous integration performance and correctness tests.
homepage: https://github.com/flutter/flutter

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  args: null
  file: null
  image: null
  meta: null
  path: null
  platform: null
  process: null
  stack_trace: null
  vm_service_client: null

  logging: null

dev_dependencies:
  # See packages/flutter_test/pubspec.yaml for why we're pinning this version.
  test: null

# PUBSPEC CHECKSUM: 0000
