# Use the parent analysis options settings and enable null-experiment.

include: ../analysis_options.yaml

analyzer:
  enable-experiment:
    - non-nullable
  errors:
    always_require_non_null_named_parameters: false # not needed with nnbd
    void_checks: false # issues with nnbd
    unnecessary_null_comparison: false
