name: string_transformer

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  front_end:
  kernel:
  vm: any

dependency_overrides:
  vm:
    path: /Users/jonahwilliams/Documents/engine/src/third_party/dart/pkg/vm