name: flutter_tools_synthetic_package
publish_to: none

environment:
  sdk: '>=2.19.0-0 <4.0.0'

dependencies:
  fake_template:
    path: ../fake_template
  flutter_tools_api:
    path: ../flutter_tools_api
