name: flutter_localizations
version: 0.0.1-dev
dependencies:
  # To update these, use "flutter update-packages --force-upgrade".

  flutter:
    sdk: flutter
  intl: 0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 2.2.0
