name: a11y_assessments
description: "A new Flutter project."

environment:
  sdk: '>=3.2.0-22.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
