name: fuchsia_remote_debug_protocol
version: 0.0.0
description: Provides an API to test/debug Flutter applications on remote Fuchsia devices and emulators.
homepage: http://flutter.dev
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  json_rpc_2: 2.2.2
  process: 4.0.0-nullsafety.4
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter


dev_dependencies:
  mockito: 4.1.1
  test: 1.16.0-nullsafety.9

# PUBSPEC CHECKSUM: 5fad
