name: web_integration
description: Integration test for web compilation.

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.6.0 <3.0.0"

flutter:
  assets:
    - lib/a.dart
    - lib/b.dart

dependencies:
  flutter:
    sdk: flutter

# PUBSPEC CHECKSUM: 0000
