name: web_integration
description: Integration test for web compilation.

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build:
  build_modules:
  build_web_compilers:
  build_runner_core:
  build_runner: 1.2.8
  _builders:
    sdk: flutter

dependency_overrides:
  build:
    path: /Users/jonahwilliams/Documents/build/build/
  build_modules:
    path: /Users/jonahwilliams/Documents/build/build_modules/
  build_web_compilers:
    path: /Users/jonahwilliams/Documents/build/build_web_compilers/
  build_runner_core:
    path: /Users/jonahwilliams/Documents/build/build_runner_core/
  build_runner:
    path: /Users/jonahwilliams/Documents/build/build_runner
# PUBSPEC CHECKSUM: d53c
