name: snippets
description: A package for parsing and manipulating code samples in Flutter repo dartdoc comments.

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  args: ^2.4.2
  dart_style: ^2.3.4
  file: ^7.0.0
  meta: ^1.12.0
  path: ^1.9.0
  platform: ^3.1.4
  process: ^5.0.2

dev_dependencies:
  test: ^1.25.2

executables:
  snippets: