name: web_e2e_tests
publish_to: none

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test: 0.9.0
  http: 0.12.0+2
  test: 1.16.0-nullsafety.5
