name: external_ui
description: A test of Flutter integrating external UIs.

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  async: 2.0.6 # TRANSITIVE DEPENDENCY
  charcode: 1.1.1 # TRANSITIVE DEPENDENCY
  collection: 1.14.6 # TRANSITIVE DEPENDENCY
  convert: 2.0.1 # TRANSITIVE DEPENDENCY
  crypto: 2.0.2+1 # TRANSITIVE DEPENDENCY
  file: 2.3.7 # TRANSITIVE DEPENDENCY
  http: 0.11.3+16 # TRANSITIVE DEPENDENCY
  http_parser: 3.1.1 # TRANSITIVE DEPENDENCY
  intl: 0.15.2 # TRANSITIVE DEPENDENCY
  json_rpc_2: 2.0.7 # TRANSITIVE DEPENDENCY
  meta: 1.1.2 # TRANSITIVE DEPENDENCY
  path: 1.5.1 # TRANSITIVE DEPENDENCY
  pub_semver: 1.3.2 # TRANSITIVE DEPENDENCY
  source_span: 1.4.0 # TRANSITIVE DEPENDENCY
  stack_trace: 1.9.2 # TRANSITIVE DEPENDENCY
  stream_channel: 1.6.4 # TRANSITIVE DEPENDENCY
  string_scanner: 1.0.2 # TRANSITIVE DEPENDENCY
  typed_data: 1.1.5 # TRANSITIVE DEPENDENCY
  vector_math: 2.0.5 # TRANSITIVE DEPENDENCY
  vm_service_client: 0.2.4+1 # TRANSITIVE DEPENDENCY
  web_socket_channel: 1.0.7 # TRANSITIVE DEPENDENCY

flutter:
  uses-material-design: true
