name: switcher
description: additional developer tooling

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  args: 1.5.1
  path: 1.6.2

# PUBSPEC CHECKSUM: 62fb
