name: flutter_goldens

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  flutter_test:
    sdk: flutter
  collection: 1.14.6
  file: 5.0.0
  meta: 1.1.2
  platform: 2.1.2
  process: 3.0.1

dev_dependencies:
  mockito: 3.0.0-alpha+3

environment:
  sdk: '>=1.19.0 <2.0.0'

# PUBSPEC CHECKSUM: 5750
