name: dev_tools
description: Various repository development tools for flutter.

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  archive: null
  args: null
  http: null
  intl: null
  meta: null
  path: null
  process: null

dev_dependencies:
  test: null
  test_api: null
  mockito: null
  file_testing: null

# PUBSPEC CHECKSUM: 0000
