name: linux_extension

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_tool_api:
    path: ../flutter_tool_api

dev_dependencies:
  test:
  mockito: