name: integration_ui
description: Flutter non-plugin UI integration tests.

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
dev_dependencies:
  test: 0.12.20
flutter:
  uses-material-design: true
