name: native_driver_test
publish_to: none

environment:
  sdk: ^3.6.0-216.0.dev

dependencies:
  native_driver:
    path: ../../tools/native_driver
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter

dev_dependencies:
  test: 1.25.8
