name: flutter_test

environment:
  # The pub client defaults to an <2.0.0 sdk constraint which we need to explicitly overwrite.
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".

  flutter:
    sdk: flutter

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so when upgrading
  # this, make sure the tests are still running correctly.
  test_core:
    git:
      url: git@github.com:jonahwilliams/test.git
      ref: refactor
      path: test_core

  # Used by golden file comparator
  path: 1.6.2

  # We use FakeAsync and other testing utilities.
  quiver: 2.0.0+1

  # We import stack_trace because the test packages uses it and we
  # need to be able to unmangle the stack traces that it passed to
  # stack_trace. See https://github.com/dart-lang/test/issues/590
  stack_trace: 1.9.3

  # Used by globalToLocal et al.
  vector_math: 2.0.8

  collection: 1.14.11 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  matcher: 0.12.3+1 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  meta: 1.1.6 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"
  typed_data: 1.1.6 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"

dev_dependencies:
  file: 5.0.6

  intl: 0.15.7 # THIS LINE IS AUTOGENERATED - TO UPDATE USE "flutter update-packages --force-upgrade"

# PUBSPEC CHECKSUM: f9f2
